package com.silanis.esl.api.model;
//
public enum CallbackEvent
{
    PACKAGE_CREATE,PACKAGE_ACTIVATE,PACKAGE_DEACTIVATE,PACKAGE_READY_FOR_COMPLETE,PACKAGE_COMPLETE,PACKAGE_TRASH,PACKAGE_RESTORE,PACKAGE_DELETE,PACKAGE_DECLINE,PACKAGE_EXPIRE,PACKAGE_OPT_OUT,DOCUMENT_SIGNED,ROLE_REASSIGN,SIGNER_COMPLETE;
}