package com.silanis.esl.sdk;

public enum ExtractionReasonCode {
    EXTRACTION_NOT_ENABLED,
    CLASSIFICATION_UNKNOWN,
    CLASSIFICATION_UNSUPPORTED_TYPE,
    CLASSIFICATION_QUALITY_WARNING,
    EXTRACTION_ERROR
}
