package com.silanis.esl.sdk;

public enum NotificationEvent {
    PACKAGE_CREATE,
    PACKAGE_ACTIVATE,
    PACKAGE_DEACTIVATE,
    PACKAGE_READY_FOR_COMPLETION,
    PACKAGE_COMPLETE,
    PACKAGE_TRASH,
    PACKAGE_RESTORE,
    PACKAGE_DELETE,
    PACKAGE_DECLINE,
    PACKAGE_OPT_OUT,
    ROLE_REASSIGN,
}
